In [1]:
import json
import pandas as pd

In [8]:
df = pd.read_csv("Data/final_tmdb_data_2000.csv.gz", low_memory = False)
df.sample(1000)

,imdb_id,adult,backdrop_path,belongs_to_collection,budget,genres,homepage,id,original_language,original_title,...,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,certification
608,tt0224086,0.0,NaN,"{'id': 432207, 'name': 'The Sex Files', 'poste...",0.0,"[{'id': 878, 'name': 'Science Fiction'}]",NaN,51767.0,en,Sexual Matrix,...,0.0,79.0,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,NaN,Sexual Matrix,0.0,6.867,15.0,R
213,tt0183488,0.0,NaN,NaN,0.0,"[{'id': 10402, 'name': 'Music'}, {'id': 35, 'n...",NaN,414787.0,en,A Man Is Mostly Water,...,0.0,110.0,[],Released,NaN,A Man Is Mostly Water,0.0,0.000,0.0,NaN
442,tt0210567,0.0,/e0rLPw4rPgXjvMjH3NwcoTWYvnl.jpg,NaN,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,34299.0,en,Beautiful,...,0.0,112.0,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,NaN,Beautiful,0.0,5.700,36.0,PG-13
1069,tt0291043,0.0,NaN,NaN,0.0,"[{'id': 80, 'name': 'Crime'}, {'id': 27, 'name...",NaN,78452.0,ko,해변으로 가다,...,0.0,91.0,"[{'english_name': 'German', 'iso_639_1': 'de',...",Released,NaN,Bloody Beach,0.0,3.800,6.0,NaN
125,tt0164212,0.0,/ca5hO15TfLe7MoAFYW6lCXwlaLX.jpg,NaN,25000000.0,"[{'id': 53, 'name': 'Thriller'}, {'id': 80, 'n...",NaN,10562.0,en,Under Suspicion,...,1308242.0,110.0,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,"In a world of secrets, the truth is never what...",Under Suspicion,0.0,6.100,379.0,R
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51,tt0144574,0.0,NaN,NaN,0.0,[],NaN,505624.0,en,Red Lipstick,...,0.0,90.0,[],Released,NaN,Red Lipstick,0.0,1.000,1.0,NaN
719,tt0238588,0.0,NaN,NaN,0.0,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",NaN,68894.0,zh,西洋镜,...,0.0,116.0,"[{'english_name': 'Mandarin', 'iso_639_1': 'zh...",Released,NaN,Shadow Magic,0.0,6.200,6.0,PG
805,tt0246875,0.0,/npuiLeBAjMF1PpJhLpwWqpt0I8M.jpg,NaN,0.0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,38294.0,en,Purely Belter,...,0.0,95.0,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,They're a couple of zeros short of a grand,Purely Belter,0.0,6.750,24.0,NaN
108,tt0160859,0.0,NaN,NaN,0.0,"[{'id': 53, 'name': 'Thriller'}]",NaN,215338.0,en,Shades of Darkness,...,0.0,88.0,[],Released,EVIL HAS ARRIVED,Shades of Darkness,0.0,0.000,0.0,NaN
535,tt0218112,0.0,/uulJ0YS8fYR1qyetKLOUfueq5Bd.jpg,NaN,0.0,"[{'id': 35, 'name': 'Comedy'}]",NaN,73642.0,en,The Closer You Get,...,0.0,93.0,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,"For five desperate Irishmen, the perfect girl ...",The Closer You Get,0.0,6.000,11.0,NaN

In [10]:
df['imdb_id']

0               0
1       tt0113026
2       tt0113092
3       tt0116391
4       tt0118694
          ...
1210    tt6174238
1211    tt7029820
1212    tt7197642
1213    tt7631368
1214    tt7802790
Name: imdb_id, Length: 1215, dtype: object